name: AmbulanceGameEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - folium
  - requests
  - pandas
  - matplotlib
  - seaborn
  - python-dotenv  
  - pip
  - pip:
      - polyline        
      - here-polyline-converter
