name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: AmbulanceGameEnv
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false

      - name: Run tests with pytest
        run: |
          conda info
          conda list
          python -m pytest
